<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete 
    <?php echo $this->escapeHtml($user->username); ?> :
    <?php echo $this->escapeHtml($user->display_name); ?> :
    <?php echo $this->escapeHtml($user->email); ?>?
    
</p>
<?php
$url = $this->url('ibmiuseradmin', array(
    'action' => 'delete',
    'user_id'     => $this->user_id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="user_id" value="<?php echo (int) $user->user_id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>