<?php

$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'ibmiuseradmin',
    array(
        'action' => 'edit',
        'user_id'     => $this->user_id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('user_id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('display_name'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag(); 