<?php

$title = 'Edit Password for User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'ibmiuseradmin',
    array(
        'action' => 'editpassword',
        'user_id'     => $this->user_id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('user_id'));
echo $this->formHidden($form->get('username'));
echo $this->formHidden($form->get('state'));
echo $this->formHidden($form->get('display_name'));
echo $this->formHidden($form->get('email'));
echo $this->formRow($form->get('password'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
?> 
<input type="submit" name="cancel" value="Cancel" />
<?php 
echo $this->form()->closeTag();
?> 