<p>
    <h2>IBM i User Admin</h2>
    <a href="<?php echo $this->url('ibmiuseradmin', array('action'=>'add'));?>">Add New User</a>
</p>

<table class="table">
<tr>
    <th>User ID</th>
    <th>Username</th>
    <th>Display Name</th>
    <th>Email</th>
    <th>State</th>
    <th>Options</th>
</tr>
<?php foreach ($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->user_id);?></td>
    <td><?php echo $this->escapeHtml($user->username);?></td>
        <td><?php echo $this->escapeHtml($user->display_name);?></td>
    <td><?php echo $this->escapeHtml($user->email);?></td>
        <td><?php echo $this->escapeHtml($user->state);?></td>
        <td>
        <a href="<?php echo $this->url('ibmiuseradmin',
            array('action'=>'edit', 'user_id' => $user->user_id));?>">Edit </a>-
        <a href="<?php echo $this->url('ibmiuseradmin',
            array('action'=>'editpassword', 'user_id' => $user->user_id));?>">Change Password </a>- 
        <a href="<?php echo $this->url('ibmiuseradmin',
            array('action'=>'delete', 'user_id' => $user->user_id));?>"> Delete</a>
    </td>
     
</tr>
<?php endforeach; ?>
</table>